services:
  # postgres:
  #   image: postgres:17  
  #   container_name: postgres-db
  #   environment:
  #     POSTGRES_USER: shubh
  #     POSTGRES_PASSWORD: 9504
  #     POSTGRES_DB: survey_db
  #     POSTGRES_PORT: 5433 
  #   ports:
  #     - "5432:5432" 
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data  

  survey-builder:
    image: survey-builder:v1
    container_name: survey-svc
    environment:
      POSTGRES_USER: shubham
      POSTGRES_PASSWORD: 9504
      POSTGRES_DB: survey_db
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5433
      PROCESSES: 1  
      WORKERS: 1         
      FAST_MODE: "false"
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
