services:
  survey-builder:
    image: survey-builder:v2
    container_name: survey-svc
    environment:
      POSTGRES_USER: shubh
      POSTGRES_PASSWORD: 9504
      POSTGRES_DB: survey_db
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      RAILWAY_PG_URL: "postgresql://postgres:xmQXiOJdGgbtGfnfsislJVqlxafWQwGj@autorack.proxy.rlwy.net:25681/railway"
      PROCESSES: 2  
      WORKERS: 1         
      FAST_MODE: "false"
      LOG_LEVEL: "INFO"
    ports:
      - "8081:8080"
    networks:
      - survey-network
networks:
  survey-network:
    external: true 
